version: '3.8'

services:
  bot:
    build: .
    container_name: plant-sense-bot
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    restart: unless-stopped
    depends_on:
      - mqtt

  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt-broker
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto:/mosquitto
